### ISSUE TITLE
Bitnami → Crunchy PGO migration

### ISSUE THREAD

**Issue by gregory-j-baker** [DTS-STN/passport-status-api#117]
This issue is intended to track the migration from Bitnami HA → Crunchy PGO.

## Steps required for migration:

1. ### Record the last execution time of the `bitnami-to-crunchy-db-backup` cron job
   ...by running the following command: (**Important:** copy this timestamp somewhere; it will be used in a later step!)

   ```  shell
   kubectl --namespace passport-status get cronjob bitnami-to-crunchy-db-backup-prod --output jsonpath='{.status.lastScheduleTime}'
   ```

1. ### Disable the `bitnami-to-crunchy-db-backup` cron job
   ...by merging <https://github.com/DTS-STN/passport-status-gitops/tree/GjB/disable-bitnami-to-crunchy-job> and running [the TeamCity GitOps job](https://teamcity.prod-dp.admin.dts-stn.com/buildConfiguration/DtsCluster_PassportStatus_PassportStatusGitOps_GitOpsOperator).

1. ### Manually sync bitnami to crunchy so it has the latest data
   ...by using the following command: (**note:** this job takes about 50 minutes to run)

   ``` shell
   kubectl create job --namespace passport-status --from cronjobs/bitnami-to-crunchy-db-backup-prod bitnami-to-crunchy-manual
   ```

1. ### Reconfigure API to use crunchy
   ...by merging <https://github.com/DTS-STN/passport-status-gitops/tree/GjB/bitnami-to-crunchy-migration> and running [the TeamCity GitOps job](https://teamcity.prod-dp.admin.dts-stn.com/buildConfiguration/DtsCluster_PassportStatus_PassportStatusGitOps_GitOpsOperator).

1. ### Verify that the new API configuration works as expected (inspect logs, perform test search, etc).

1. ### Copy any bitnami data that was generated after step 2
   ...by applying the following manifest:

   **⚠️ Important note:** replace the `TIMESTAMP` value with the timestamp recorded in step 1

   ``` yaml
   apiVersion: batch/v1
   kind: Job
   metadata:
     name: passport-status-db-backup
     namespace: passport-status
   spec:
     backoffLimit: 0
     template:
       spec:
         restartPolicy: Never
         containers:
           - name: db-copy
             image: docker.io/postgres:15
             env:
               #
               # prod
               # SRC: crunchy; DST: bitnami
               #
               - name: SRCHOST
                 value: prod-postgresql-ha-pgpool.passport-status.svc
               - name: SRCDB
                 value: passport-status
               - name: SRCUSER
                 value: passport-status
               - name: SRCPASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: prod-postgresql-ha-postgresql
                     key: postgresql-password
               - name: DSTHOST
                 value: passport-status-db-prod-primary.passport-status.svc
               - name: DSTDB
                 value: passport-status
               - name: DSTUSER
                 value: passport-status
               - name: DSTPASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: passport-status-db-prod-pguser-passport-status
                     key: password
             command: ['/bin/bash', '-c']
             args:
               - >
                 export TIMESTAMP="2023-11-14T12:43:26Z";
                 export TABLES="email_request event_log http_request passport_status source_code status_code";
                 export PGHOST=$SRCHOST;
                 export PGUSER=$SRCUSER;
                 export PGPASSWORD=$SRCPASSWORD;
                 export PGDATABASE=$SRCDB;
                 for TABLE in $TABLES;
                 do
                   psql --command "\COPY (SELECT * FROM $TABLE WHERE created_date >= '$TIMESTAMP') TO '/tmp/$TABLE.csv';";
                 done
                 &&
                 for TABLE in $TABLES;
                 do
                   cat /tmp/$TABLE.csv;
                 done
                 &&
                 export PGHOST=$DSTHOST;
                 export PGUSER=$DSTUSER;
                 export PGPASSWORD=$DSTPASSWORD;
                 export PGDATABASE=$DSTDB;
                 for TABLE in $TABLES;
                 do
                   echo "
                     BEGIN;
                     CREATE TEMP TABLE tmp_$TABLE AS (SELECT * FROM $TABLE) WITH NO DATA;
                     \COPY tmp_$TABLE FROM '/tmp/$TABLE.csv';
                     INSERT INTO $TABLE (SELECT * FROM tmp_$TABLE) ON CONFLICT DO NOTHING;
                     COMMIT;
                   " | psql
                 done
   ```

1. ### 🍻 🍷 🥃 

## References

- <https://teamcity.prod-dp.admin.dts-stn.com/buildConfiguration/DtsCluster_PassportStatus_PassportStatusGitOps_GitOpsOperator>
- <https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/connect-cluster>
- <https://github.com/DTS-STN/passport-status-gitops/tree/GjB/disable-bitnami-to-crunchy-job>
- <https://github.com/DTS-STN/passport-status-gitops/tree/GjB/bitnami-to-crunchy-migration>
